[project]
name = "todolist"
version = "0.1.0"
description = "To Do List feita em Python, Flet e Banco de dados"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Philipi José",      email = "philipi.rodrigues342@gmail.com" },
    { name = "Guilherme Valadão", email = "valadaodenovo@gmail.com"        }
]
dependencies = [
  "flet==0.27.6",
  "SQLAlchemy==2.0.38",
  "python-dotenv==1.0.1",
  "PyMySQL==1.1.1"
]

[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.Philipi"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "todolist"

# company name to display in about app dialogs
company = "Philipi"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2025 by Flet"

[tool.flet.app]
path = "src"

[tool.uv]
dev-dependencies = [
    "flet[all]==0.27.6",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.27.6"}

[tool.briefcase]
project_name = "todolist"
license = "MIT"
formal_name = "To Do List Philipi Valadão"
bundle = "com.Philipi.todolist"
sources = ["src"]
description = "To Do List feita em Python, Flet e Banco de dados"
version = "0.1.0"

[tool.briefcase.app.src]